language: java
jdk:
  - oraclejdk8
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
install:
  - mvn clean --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/datajack-properties-adaptor
      branch: master
      jdk: oraclejdk8
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/datajack-properties-adaptor
      tags: true
      jdk: oraclejdk8
notifications:
  email: false